---
title: "bootstrapping"
author: "yz5248"
date: "2025-11-13"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(p8105.datasets)

set.seed(1)
```

```{r}
n_samp = 250

sim_df_const = 
  tibble(
    x = rnorm(n_samp, 1, 1),
    error = rnorm(n_samp, 0, 1),
    y = 2 + 3 * x + error
  )

sim_df_nonconst = sim_df_const |> 
  mutate(
  error = error * .75 * x,
  y = 2 + 3 * x + error
)
```

```{r}
sim_df = 
  bind_rows(const = sim_df_const, nonconst = sim_df_nonconst, .id = "data_source") 

sim_df |> 
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = .5) +
  stat_smooth(method = "lm") +
  facet_grid(~data_source) 
```

look at this data
```{r}
sim_df_nonconst |>
  ggplot(aes(x = x, y = y)) +
  geom_point()
```

```{r}
sim_df_const |>
  lm(y ~ x, data = _) |> 
  broom::tidy() |> 
  knitr::kable(digits = 3)

sim_df_nonconst |>
  lm(y ~ x, data = _) |> 
  broom::tidy() |> 
  knitr::kable(digits = 3)
```

write a function to draw a bootstrap sample
```{r}
boot_sample = function(df) {
  sample_frac(df, size = 1, replace = TRUE)
}

# does it work?
sim_df_nonconst |> 
  boot_sample() |> 
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = .5) +
  stat_smooth(method = "lm") +
  xlim(c(-2,4)) +
  ylim(c(-5, 16))
```

```{r}
boot_straps = 
  tibble(
    iter = 1:10
  ) |> 
  mutate(
    bootstrap_sample = map(iter, \(i) boot_sample(df = sim_df_nonconst))
  )

boot_straps
```

```{r}
boot_straps |> 
  pull(bootstrap_sample) |> 
  nth(2) |>
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = .5) +
  geom_smooth(method = "lm", se = FALSE) +
  xlim(c(-2,4)) +
  ylim(c(-5, 16))
```

actually run my analysis
```{r}
bootstrap_results = 
  boot_straps |>
  mutate(
    fits = map(bootstrap_sample, \(df) lm(y ~ x, data = df)),
    results = map(fits, broom::tidy)
  )
```

look at result
```{r}
bootstrap_results |>
  select(iter, results) |>
  unnest(results)

bootstrap_results |>
  select(iter, results) |>
  unnest(results) |>
  group_by(term) |>
  summarise(
    mean = mean(estimate),
    se = sd(estimate)
  )
```

```{r}
bootstrap_results |>
  select(iter, results) |>
  unnest(results) |>
  filter(term == "x") |>
  ggplot(aes(x = estimate)) +
  geom_density()
```

```{r}
bootstrap_results |>
  select(iter, results) |>
  unnest(results) |>
  group_by(term) |>
  summarise(
    ci_lower = quantile(estimate, 0.025),
    ci_upper = quantile(estimate, 0.975)
  )
```

## do it again but faster
```{r}
sim_df_nonconst |>
  bootstrap(n = 10) |>
  mutate(
    df = map(strap, as_tibble),
    fits = map(df, \(df) lm(y ~ x, data = df)),
    results = map(fits, broom::tidy)
  ) |>
  select(.id, results)|>
  unnest(results)
```


```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough != "Staten Island") |> 
  drop_na(price, stars) |> 
  select(price, stars, borough, neighborhood, room_type)
```

```{r}
nyc_airbnb |> 
  ggplot(aes(x = stars, y = price, color = room_type)) + 
  geom_point() 
```

```{r}
airbnb_bootstrap_results =
  nyc_airbnb |>
  filter(borough == "Manhattan") |> 
  modelr::bootstrap(n = 10) |> 
  mutate(
    df = map(strap, as_tibble),
    fits = map(df, \(df) lm(price ~ stars + room_type, data = df)),
    results = map(fits, broom::tidy)) |> 
  select(.id, results) |> 
  unnest(results) 
```

```{r}
airbnb_bootstrap_results |>
  filter(term == "stars") |> 
  ggplot(aes(x = estimate)) + 
  geom_density()
```

